title: JOSEPH ATUNDE
logo: mr joseph Photo.jpg 
description: I am a statistical analyst and I am very proficient in the use of statistical tool and programming languages for statistical analysis. 
show download: true
theme: jekyll-theme-minimal
